# Site settings
title: MetaDaTV // End-to-End TV Metadata
email: camille.guinaudeau@limsi.fr
description: > # this means to ignore newlines until "baseurl:"
  MetaDaTV is funded by ANR, the French research funding agency.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metadatv.limsi.fr" # the base hostname & protocol for your site
# twitter_username: metadatv
github_username:  metadatv

# Build settings
markdown: kramdown
